### ISSUE TITLE
Converting problem

### ISSUE THREAD

**Issue by RememberForgottenHits** [HDInnovations/xbtitfm-to-unit3d#1]
What is wrong or how to i can convert xbtitfm database to unit DB?

root@omade:/var/www/html# php artisan unit3d:from-xbtitfm --database='xbtitfm' --username='root' --password='89jaiK2Md4' -v

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: insert into `users` (`id`, `username`, `password`, `passkey`, `rsskey`, `group_id`, `email`, `uploaded`, `downloaded`, `seedbonus`, `image`, `title`, `about`, `signature`, `hitandruns`, `active`, `invites`, `last_login`, `created_at`, `updated_at`) values (1, Guest, , 00000000000000000000000000000000, 8670389f85afe0114b91304e6d30a5bd, 3, none, 0, 0, 0.900000, ?, ?, , , 0, 1, 0, 2014-02-19 05:44:31, 2014-02-19 05:44:31, 2020-04-09 13:36:15))

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  3   PDOStatement::execute()
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  4   Doctrine\DBAL\Driver\PDOStatement::execute()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:463

  5   Illuminate\Database\Connection::Illuminate\Database\{closure}()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:662

  6   Illuminate\Database\Connection::runQueryCallback()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:629

  7   Illuminate\Database\Connection::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:464

  8   Illuminate\Database\Connection::statement()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:416

  9   Illuminate\Database\Connection::insert()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32

  10  Illuminate\Database\Query\Processors\Processor::processInsertGetId()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2695

  11  Illuminate\Database\Query\Builder::insertGetId()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1366

  12  Illuminate\Database\Eloquent\Builder::__call()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:839

  13  Illuminate\Database\Eloquent\Model::insertAndSetId()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:804

  14  Illuminate\Database\Eloquent\Model::performInsert()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:667

  15  Illuminate\Database\Eloquent\Model::save()
      /var/www/html/vendor/hdinnovations/xbtitfm-to-unit3d/src/Functionality/Imports.php:56

  16  HDInnovations\XbtitFmToUnit3d\Functionality\Imports::import()
      /var/www/html/vendor/hdinnovations/xbtitfm-to-unit3d/src/Functionality/Imports.php:34

  17  HDInnovations\XbtitFmToUnit3d\Functionality\Imports::importTable()
      /var/www/html/vendor/hdinnovations/xbtitfm-to-unit3d/src/Commands/FromXbtitFm.php:90

  18  HDInnovations\XbtitFmToUnit3d\Commands\FromXbtitFm::importUsers()
      /var/www/html/vendor/hdinnovations/xbtitfm-to-unit3d/src/Commands/FromXbtitFm.php:58

  19  HDInnovations\XbtitFmToUnit3d\Commands\FromXbtitFm::handle()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  20  call_user_func_array()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  21  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php:36

  22  Illuminate\Container\Util::unwrapIfClosure()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  23  Illuminate\Container\BoundMethod::callBoundMethod()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  24  Illuminate\Container\BoundMethod::call()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:590

  25  Illuminate\Container\Container::call()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:134

  26  Illuminate\Console\Command::execute()
      /var/www/html/vendor/symfony/console/Command/Command.php:255

  27  Symfony\Component\Console\Command\Command::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:121

  28  Illuminate\Console\Command::run()
      /var/www/html/vendor/symfony/console/Application.php:1001

  29  Symfony\Component\Console\Application::doRunCommand()
      /var/www/html/vendor/symfony/console/Application.php:271

  30  Symfony\Component\Console\Application::doRun()
      /var/www/html/vendor/symfony/console/Application.php:147

  31  Symfony\Component\Console\Application::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:93

  32  Illuminate\Console\Application::run()
      /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131

  33  Illuminate\Foundation\Console\Kernel::handle()
      /var/www/html/artisan:37

**Comment by HDVinnie** [comment]
Truncate the table before trying to port your DB over. You have UNIT3D default seeded data in the users table.

**Comment by RememberForgottenHits** [comment]
Thanks for answer.
It's work but now small problem. How to fix INCORRECT DATETIME VALUE?

sysop@omade:/var/www/html$ sudo php artisan unit3d:from-xbtitfm --database='xbtitfm' --username='myusername' --password='mypassword'
[sudo] password for sysop: 

   Illuminate\Database\QueryException  : SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1000-01-01 00:00:00' for column 'updated_at' at row 1 (SQL: insert into `torrents` (`info_hash`, `file_name`, `name`, `slug`, `user_id`, `imdb`, `tvdb`, `sticky`, `free`, `anon`, `size`, `category_id`, `type`, `announce`, `num_file`, `description`, `seeders`, `leechers`, `times_completed`, `created_at`, `updated_at`) values (1058e3e37b2b5faecb54110e968c9e7c59315c02, 1058e3e37b2b5faecb54110e968c9e7c59315c02.btf, 2 Quick Start &quot;2010&quot; 2010 (MP3-265), 2-quick-start-quot-2010-quot-2010-mp3-265, 2, 0, 0, 0, 0, 1, 96322298, 69, 14, , 0, ---------------------------------------------------------------------
                        2 Quick Start - 2010
---------------------------------------------------------------------

Artist...............: 2 Quick Start
Album................: 2010
Genre................: 
Source...............: CD
Year.................: 2010
Ripper...............: EAC (Secure mode) / LAME 3.92 & Asus CD-S520
Codec................: LAME 3.99
Version..............: MPEG 1 Layer III
Quality..............: Extreme, (avg. bitrate: 265kbps)
Channels.............: Joint Stereo / 44100 hz
Tags.................: ID3 v1.1, ID3 v2.3

---------------------------------------------------------------------
                       Tracklisting
---------------------------------------------------------------------

   1. 2 Quick Start - Saladus                                 [03:25]
   2. 2 Quick Start - A -ga alagavad                          [03:40]
   3. 2 Quick Start - Teineteiseta                            [03:31]
   4. 2 Quick Start - Kolm soovi                              [04:33]
   5. 2 Quick Start - Kõik see, mida teed                     [03:42]
   6. 2 Quick Start - Midagi ammust ja midagi uut             [04:22]
   7. 2 Quick Start - Viimased read                           [04:11]
   8. 2 Quick Start - Kuum                                    [04:37]
   9. 2 Quick Start - Tuled ja saad lähed ja viid             [04:08]
  10. 2 Quick Start - Videvikus                               [04:04]
  11. 2 Quick Start - Kuidas sa saad                          [03:33]
  12. 2 Quick Start - Jälle alguses                           [04:13]

Playing Time.........: 48:04
Total Size...........: 91,86 MB
, 0, 0, 0, 2020-01-01 03:57:43, 1000-01-01 00:00:00))

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1000-01-01 00:00:00' for column 'updated_at' at row 1")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123

  2   PDOException::("SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1000-01-01 00:00:00' for column 'updated_at' at row 1")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121

  Please use the argument -v to see more details.

**Comment by RememberForgottenHits** [comment]
Problem solved this ==> Open your config/database.php file, and make sure your database connection shows 'strict' => false.
